container_image_be     = "jungin7612/calc-be:latest"
container_image_fe     = "jungin7612/calc-fe:latest"
frontend_url           = "http://localhost:30030"
backend_url            = "http://localhost:30031"
kubernetes_config_path = "~/.kube/config"
